tokenizer:
  model_name: /flan-t5-base-warm-up-v6/checkpoint-9000
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  id: exact_match 
  args:
    think: True

datapool:
  id: ambignq
  args:
    prompt_prefix: "### Instruction:\nPlease answer the following questions using the shortest possible response. For example, if the question asks 'What is the capital of France?', you can simply reply with '[Answer] Paris'. If you need to retrieval additional relevant knowledge, rewrite the question to a better query, such as '[Query] The capital of France'. \n\n### Input:\n"
    prompt_suffix: "\n\n### Response:\n" 

    ifdebug: False

env:
  n_envs: 10 # 10
  args:
    max_prompt_length: 512
    max_episode_length: 50
    terminate_on_eos: True
    prompt_truncation_side: "right"
    context_start_token: 0
    retrieval_cost: -0.5

alg:
  id: ppo
  model_type: seq2seq 
  args: 
    n_steps: 512 # 256 # 32
    batch_size: 32 # 
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 2 # 4 # 2
    ent_coef: 0.0
  kl_div:
    coeff: 0.001
    target_kl: 0.2
  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: /flan-t5-base-warm-up-v6/checkpoint-9000
      apply_model_parallel: True 
      
      prompt_truncation_side: "right"
      generation_kwargs:
        do_sample: True
        top_k: 50

train_evaluation:
  eval_batch_size: 16
  n_iters: 100
  eval_every: 5 # 10
  save_every: 5 # 10
  metrics:
    - id: exact_match # rouge
      args:
        use_single_ref: False

  generation_kwargs:
    num_beams: 4

# reward = -0.05 (both side)
# 修改base model为sft的时候为topk形式的
# 同时要尝试不是要降低exploration
# 加入retrieval_cost = -0.6, 看看能不能让模型不完全去retrieval
# 修改hit原理，如果hit了，retrieval_cost = -0.1
# 修改了policy_loss = -policy_loss_2.mean()， 不要了policy_loss1了，可能会出现极端值