tokenizer:
  model_name: /mnt/workspace/user/gaojingsheng/LLM/checkpoint/llama2-7b-chat-hf
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  id: exact_match 
  args:
    think: True

datapool:
  id: popqa
  args:
    prompt_prefix: "Please first determine whether answering the following question requires additional relevant knowledge. If so, rewrite the question to better fit retrieval query. Output in the format: {'query': **}. If no additional knowledge is needed, please answer the question directly, output in the format '{'answer': **}'. Question: "
    prompt_suffix: " Output: " 

    ifdebug: True

env:
  n_envs: 1 # 10
  args:
    max_prompt_length: 512
    max_episode_length: 50
    terminate_on_eos: True
    prompt_truncation_side: "right"
    context_start_token: 0

alg:
  id: ppo
  model_type: causal 
  args: 
    n_steps: 256 # 256 # 32
    batch_size: 4 # 
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 2 # 4 # 2
    ent_coef: 0.0
  kl_div:
    coeff: 0.001
    target_kl: 0.2
  policy:
    id: causal_lm_actor_critic_policy
    args:
      model_name: /mnt/workspace/user/gaojingsheng/LLM/checkpoint/llama2-7b-chat-hf
      apply_model_parallel: True
      # 不并行就OOM,并行就有bug
      prompt_truncation_side: "right"
      generation_kwargs:
        do_sample: True
        top_k: 50

train_evaluation:
  eval_batch_size: 16
  n_iters: 500 # 50
  eval_every: 50 # 10
  save_every: 50 # 10
  metrics:
    - id: exact_match # rouge
      args:
        use_single_ref: False

  generation_kwargs:
    num_beams: 4

