tokenizer:
  model_name: /mnt/workspace/user/gaojingsheng/LLM/checkpoint/flan-t5-base
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  id: rouge_l_max
  args:
    max_n: 4
    limit_length: True
    length_limit: 100
    length_limit_type: "words"
    apply_avg: True
    apply_best: True
    alpha: 0.5
    weight_factor: 1.2
    stemming: True

datapool:
  id: narrative_qa_retrieval
  args:
    prompt_prefix: "Please first determine whether the following question requires additional relevant knowledge retrieval. If so, rewrite the question to better fit retrieval query. Output in the format: {'retrieval': 'yes', 'query': query}. If no retrieval is needed, please answer the question directly, in the format {'retrieval': no, 'answer': answer}. The question is: "
    # prompt_prefix: "Please answer this question in the format of {'retrieval': 'no', 'answer': answer}, you can refer to relevant knowledge: knowledge. The question is: "

  # ifdebug: True


env:
  n_envs: 1 # 10
  args:
    max_prompt_length: 512
    max_episode_length: 50
    terminate_on_eos: True
    prompt_truncation_side: "right"
    context_start_token: 0

alg:
  id: ppo
  args: 
    n_steps: 32 # 256 # 32
    batch_size: 2 # 4 # # 64 # 8 ~ 47G显存
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 2 
    ent_coef: 0.0
  kl_div:
    coeff: 0.001
    target_kl: 0.2
  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: /mnt/workspace/user/gaojingsheng/LLM/checkpoint/flan-t5-base
      apply_model_parallel: True
      prompt_truncation_side: "right"
      generation_kwargs:
        do_sample: True
        top_k: 50

train_evaluation:
  eval_batch_size: 16
  n_iters: 50
  eval_every: 10
  save_every: 10
  metrics:
    - id: rouge
      args:
        use_single_ref: False

  generation_kwargs:
    num_beams: 4

